name: Deploy
on:
  push:
    branches:
      - master
    paths:
        - 'src/**'
        - 'cdk.json'
        - 'package.json'
        - 'package-lock.json'
        - 'tsconfig.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm ci

      - name: Test
        run: |
          npm test

      - name: Deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_args: '--require-approval never'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'
