name: Pull Request
on:
    pull_request:
        types: [ opened, synchronize, labeled ]
        branches:
            - 'master'

concurrency:
    group: ${{ github.head_ref }}
    cancel-in-progress: true

jobs:

    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Install Dependencies
                run: |
                    npm ci

            -   name: Test
                run: |
                    npm run lint

    test:
        name: Unit Test
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Install Dependencies
                run: |
                    npm ci

            -   name: Test
                run: |
                    npm test

    synth:
        name: Synthesize
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Install Dependencies
                run: |
                    npm ci

            -   name: Synthesize
                uses: youyo/aws-cdk-github-actions@v2
                with:
                    cdk_subcommand: 'synth'
                    cdk_args: '--require-approval never'
                    actions_comment: false
                env:
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    AWS_DEFAULT_REGION: 'us-west-2'
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    STAGE: 'prod'

    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: [ lint, test, synth ]
        steps:

            -   name: Set up Slug action
                uses: rlespinasse/github-slug-action@v3.x

            -   name: Init STAGE variable
                run: echo "STAGE=pr-${{ github.event.number }}-${{ env.GITHUB_HEAD_REF_SLUG }}" >> $GITHUB_ENV

            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Install Dependencies
                run: |
                    npm ci

            -   name: Deploy
                uses: youyo/aws-cdk-github-actions@v2
                with:
                    cdk_subcommand: 'deploy'
                    cdk_args: '--require-approval never'
                    actions_comment: false
                env:
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    AWS_DEFAULT_REGION: 'us-west-2'
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    STAGE: ${{ env.STAGE }}

            -   name: Successful Deployment Comment
                uses: thollander/actions-comment-pull-request@v2
                with:
                    message: |
                        # Success ✅
                        The api was successfully deploy and available at https://${{ env.STAGE }}.api.helpfl.click

    e2e:
        name: E2E Test
        runs-on: ubuntu-latest
        needs: [ deploy ]
        steps:
            -   name: Set up Slug action
                uses: rlespinasse/github-slug-action@v3.x

            -   name: Init STAGE variable
                run: echo "STAGE=pr-${{ github.event.number }}-${{ env.GITHUB_HEAD_REF_SLUG }}" >> $GITHUB_ENV

            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Install Dependencies
                run: |
                    npm ci

            -   name: E2E Test
                run: |
                    npm run test:e2e
                env:
                    STAGE: ${{ env.STAGE }}

    diff:
        name: Diff
        runs-on: ubuntu-latest
        needs: [ e2e, deploy ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Install Dependencies
                run: |
                    npm ci

            -   name: Diff
                uses: youyo/aws-cdk-github-actions@v2
                with:
                    cdk_subcommand: 'diff'
                    cdk_args: '--require-approval never'
                    actions_comment: true
                env:
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    AWS_DEFAULT_REGION: 'us-west-2'
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    STAGE: 'prod'

